# Generated by Django 2.1.2 on 2018-11-11 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Титул задачи')),
                ('body', models.TextField(verbose_name='Тела задачи')),
                ('status', models.CharField(choices=[('NW', 'Новый'), ('WR', 'В работе'), ('TS', 'Тестирование'), ('FSH', 'Выполнено')], default='NW', max_length=3, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('NR', 'Нормальный'), ('UG', 'Срочный'), ('HG', 'Высокий'), ('IT', 'Немедленный')], default='NR', max_length=2, verbose_name='Приоритет')),
                ('create_date', models.DateField(auto_now=True)),
                ('death_line', models.DateField(verbose_name='Дедлине')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
            ],
        ),
        migrations.RemoveField(
            model_name='todolists',
            name='owner',
        ),
        migrations.DeleteModel(
            name='TodoLists',
        ),
    ]
